=head1 NAME

gbatch_jobdel - delete a job

=head1 SYNOPSIS

=for man
\&\fB#include <gbatch.h>\fR
.PP

=for html
<STRONG>#include &lt;gbatch.h&gt;</STRONG>
<br>

B<int gbatch_jobdel(const int>
I<fd>B<, const unsigned>
I<flags>B<, const slotno_t>
I<slot>B<)>

=head1 DESCRIPTION

The function B<gbatch_jobdel> is used to delete a job.

I<fd> is a file descriptor which was previously returned by a
successful call to gbatch_open(3).

I<flags> is zero or C<GBATCH_FLAG_IGNORESEQ> to ignore recent changes
to the job list.

I<slot> is the slot number corresponding to the job as returned by
gbatch_joblist(3) or xb_jobfindslot(3).

=head1 RETURN VALUES

The function returns 0 if successful, otherwise an error code as
defined in the include file \fBgbatch.h\fR.

=head1 EXAMPLE

To delete all jobs for a user.

 int fd, ret, cnt, numjobs;
 slotno_t *list;

 fd = gbatch_open("myhost", (char *) 0);
 ret = gbatch_joblist(fd, GBATCH_FLAG_USERONLY, &numjobs, &list);
 if (fd < 0)  { /* handle error */
     . . .
 }

 for (cnt = 0; cnt < numjobs; cnt++)  {
     if ((ret = gbatch_jobdel(fd, GBATCH_FLAG_IGNORESEQ, list[cnt])  {
         /* handle error */
         . . .
     }
 }

 gbatch_close(fd);

=head1 SEE ALSO

gbatch_jobadd(3),
gbatch_jobfind(3),
gbatch_joblist(3),
gbatch_jobop(3),
gbatch_jobread(3),
gbatch_jobupd(3).

=head1 COPYRIGHT

Copyright (c) 2009 Free Software Foundation, Inc.
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
