=head1 NAME

gbatch_putredir - insert a new redirection in a job structure

=head1 SYNOPSIS

=for man
\&\fB#include <gbatch.h>\fR
.PP

=for html
<STRONG>#include &lt;gbatch.h&gt;</STRONG>
<br>

B<int gbatch_putredir(apiBtjob *>I<jobp>B<, const unsigned>
I<indx>B<, const apiMredir *>I<newredir>B<)>

=head1 DESCRIPTION

The function B<gbatch_putredir> is used to insert a new or replacement
redirection into a job structure.

I<jobp> is a pointer to a structure containing the job details.

I<indx> is the number of the redirection to be inserted or
replaced (starting at zero). This should be equal to the number of
existing redirections to create a new one.

I<newredir> is the redirection structure representing the redirection
to be inserted or replaced.

=head1 RETURN VALUES

The result will be no-zero if successful or zero if the string table
overflowed.  In the latter case the string table contents of the job
should not be relied upon.  The job structure should be saved first if
in doubt.

=head1 SEE ALSO

gbatch_delarg(3),
gbatch_delenv(3),
gbatch_delredir(3),
gbatch_getarg(3),
gbatch_getdirect(3),
gbatch_getenv(3),
gbatch_getenvlist(3),
gbatch_gethenv(3),
gbatch_getredir(3),
gbatch_gettitle(3),
gbatch_putarg(3),
gbatch_putarglist(3),
gbatch_putdirect(3),
gbatch_putenv(3),
gbatch_putenvlist(3),
gbatch_puttitle(3),
gbatch_setqueue(3).

=head1 COPYRIGHT

Copyright (c) 2009 Free Software Foundation, Inc.
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
