=head1 NAME

gbatch_getbtu - read a user profile

=head1 SYNOPSIS

=for man
\&\fB#include <gbatch.h>\fR
.PP

=for html
<STRONG>#include &lt;gbatch.h&gt;</STRONG>
<br>

B<int gbatch_getbtu(const int>
I<fd>B<, char *>I<username>B<, char *>I<groupname>B<, apiBtuser *>I<ustr>B<)>

=head1 DESCRIPTION

The function B<gbatch_getbtu> is used to read the user profile of a
specific user. Only a user with I<read admin file> privilege will be
able to read the profiles of other users.

I<fd> is a file descriptor which was previously returned by a
successful call to gbatch_open(3).

I<username> is the name of a valid user on the server or null to fetch details for
the currently-logged in user.

I<groupname> will be assigned with the default group name on the server.

I<ustr> is a pointer to a structure which will on successful return,
contain the profile of the specific user.

=head1 RETURN VALUES

The function returns 0 if successful, otherwise an error code as
defined in the include file \fBgbatch.h\fR.

=head1 SEE ALSO

gbatch_getbtd(3),
gbatch_open(3),
gbatch_putbtd(3),
gbatch_putbtu(3).

=head1 COPYRIGHT

Copyright (c) 2009 Free Software Foundation, Inc.
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
