=head1 NAME

gbatch_ciupd - update a command interpreter

=head1 SYNOPSIS

=for man
\&\fB#include <gbatch.h>\fR
.PP

=for html
<STRONG>#include &lt;gbatch.h&gt;</STRONG>
<br>

B<int gbatch_ciupd(const int>
I<fd>B<, const unsigned>
I<flags>B<, const int>
I<indx>B<, const Cmdint *>I<newci>B<)>

=head1 DESCRIPTION

The function B<gbatch_ciupd> is used to update the details of a command
interpreter on a B<GNUbatch> server. The invoking user must have
I<special create> permission or the call will be rejected.

I<fd> is a file descriptor which was previously returned by a
successful call to gbatch_open(3).

I<flags> is currently unused, but is reserved for future extensions.

I<indx> is the number of the command interpreter to be updated (see gbatch_ciread(3)).

I<newci> is a pointer to a structure containing the new command
interpreter details.

=head1 RETURN VALUES

The function returns 0 if successful, otherwise an error code as
defined in the include file \fBgbatch.h\fR.

=head1 SEE ALSO

gbatch_ciadd(3),
gbatch_cidel(3),
gbatch_ciread(3).

=head1 COPYRIGHT

Copyright (c) 2009 Free Software Foundation, Inc.
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
