=head1 NAME

gbatch_getarg - extract an argument string from a job

=head1 SYNOPSIS

=for man
\&\fB#include <gbatch.h>\fR
.PP

=for html
<STRONG>#include &lt;gbatch.h&gt;</STRONG>
<br>

B<const char *gbatch_getarg(const apiBtjob *>I<jobp>B<, const unsigned>
I<indx>B<)>

=head1 DESCRIPTION

The function B<gbatch_getarg> is used to extract an argument string from a
job string table.

I<jobp> is a pointer to a structure containing the details of the job.

I<indx> is the argument number required. This should be between 0 and
1 less than the total number of arguments (given by the field
C<jobp->h.bj_args>).

=head1 RETURN VALUES

If successful the function will return the required argument as a
C<const> character string otherwise C<NULL> if the argument number is invalid.

=head1 SEE ALSO

gbatch_delarg(3),
gbatch_delenv(3),
gbatch_delredir(3),
gbatch_getdirect(3),
gbatch_getenv(3),
gbatch_getenvlist(3),
gbatch_gethenv(3),
gbatch_getredir(3),
gbatch_gettitle(3),
gbatch_putarg(3),
gbatch_putarglist(3),
gbatch_putdirect(3),
gbatch_putenv(3),
gbatch_putenvlist(3),
gbatch_putredir(3),
gbatch_putredirlist(3),
gbatch_puttitle(3),
gbatch_setqueue(3).

=head1 COPYRIGHT

Copyright (c) 2009 Free Software Foundation, Inc.
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
