=head1 NAME

gbatch_ciread - read the list of command interpreters

=head1 SYNOPSIS

=for man
\&\fB#include <gbatch.h>\fR
.PP

=for html
<STRONG>#include &lt;gbatch.h&gt;</STRONG>
<br>

B<int ciread(const int>
I<fd>B<, const unsigned>
I<flags>B<, int *>I<numcis>B<, Cmdint **>I<cilist>B<)>

=head1 DESCRIPTION

The function B<gbatch_ciread> is used to read the list of command
interpreters from the given server. This may be invoked by any user,
no special permission is required.

I<fd> is a file descriptor which was previously returned by a
successful call to gbatch_open(3).

I<flags> is currently unsused, but is reserved for future use.

I<numcis> is a pointer to an integer which upon return will contain
the number of command interpreter structures returned in
I<cilist>. (This might exceed the number of actual command interpeters
if some have been deleted).

I<cilist> is a pointer to which a vector of command interpreter
structures will be assigned by this routine. The user should not
attempt to free the memory used by this structure as it is owned by
the API. The list returned may possibly have "holes" in it where
previously-created command interpreters have been deleted. These holes
can be identified by having a null C<ci_name> field.

The index number of each element in the vector is the number which
should be used as the third argument in gbatch_cidel(3) and xb_ciupd(3)
calls.

=head1 RETURN VALUES

=for html
<P>The function returns 0 if successful otherwise one of the error codes
<A HREF="#Error_codes">listed in the start of this chapter</A>.</P>

=for man
The function returns 0 if successful, otherwise an error code as
defined in the include file \fBgbatch.h\fR.

=head1 SEE ALSO

gbatch_ciadd(3),
gbatch_cidel(3),
gbatch_ciupd(3).

=head1 COPYRIGHT

Copyright (c) 2009 Free Software Foundation, Inc.
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
