=head1 NAME

gbatch_varrename - rename a variable

=head1 SYNOPSIS

=for man
\&\fB#include <gbatch.h>\fR
.PP

=for html
<STRONG>#include &lt;gbatch.h&gt;</STRONG>
<br>

B<int gbatch_varrename(const int>
I<fd>B<, const unsigned>
I<flags>B<, const slotno_t>
I<slot>B<, const char *>I<newname>B<)>

=head1 DESCRIPTION

The function B<gbatch_varrename> is used to change the name of a variable

I<fd> is a file descriptor which was previously returned by a
successful call to gbatch_open(3).

I<flags> is zero or C<GBATCH_FLAG_IGNORESEQ> to ignore recent changes
to the variable list.

I<slot> is the slot number corresponding to the variable as returned
by gbatch_varlist(3) or xb_varfindslot(3).

I<newname> is the proposed new name for the variable.

=head1 RETURN VALUES

The function returns 0 if successful, otherwise an error code as
defined in the include file \fBgbatch.h\fR.

=head1 SEE ALSO

gbatch_varadd(3),
gbatch_varchcomm(3),
gbatch_varchgrp(3),
gbatch_varchmod(3),
gbatch_varchown(3),
gbatch_vardel(3),
gbatch_varfind(3),
gbatch_varlist(3),
gbatch_varmon(3),
gbatch_varread(3),
gbatch_varupd(3).

=head1 COPYRIGHT

Copyright (c) 2009 Free Software Foundation, Inc.
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
