=head1 NAME

gbatch_putbtu - update user permissions

=head1 SYNOPSIS

=for man
\&\fB#include <gbatch.h>\fR
.PP

=for html
<STRONG>#include &lt;gbatch.h&gt;</STRONG>
<br>

B<int gbatch_putbtu(const int>
I<fd>B<, const char *>
I<username>B<, const apiBtuser *>I<ustr>B<)>

=head1 DESCRIPTION

The function B<gbatch_putbtu> is used to update a user's profile
parameters for the given host. It may only be invoked by a user with
I<write admin file> privilege, unless the user just wants to change
his or her default modes and has I<change default modes>
privilege. (The privileges are those applying prior to the operation).

I<fd> is a file descriptor which was previously returned by a
successful call to gbatch_open(3).

I<username> is the name of the user, whose details are being updated.

I<ustr> is a pointer to a structure which contains the new user
profile.

=head1 RETURN VALUES

The function returns 0 if successful, otherwise an error code as
defined in the include file \fBgbatch.h\fR.

=head1 SEE ALSO

gbatch_getbtd(3),
gbatch_getbtu(3),
gbatch_open(3),
gbatch_putbtd(3).

=head1 COPYRIGHT

Copyright (c) 2009 Free Software Foundation, Inc.
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
