=head1 NAME

gbatch_getbtd - get the defaut user profile

=head1 SYNOPSIS

=for man
\&\fB#include <gbatch.h>\fR
.PP

=for html
<STRONG>#include &lt;gbatch.h&gt;</STRONG>
<br>

B<int gbatch_getbtd(const int>
I<fd>B<, apiBtdef *>I<defs>B<)>

=head1 DESCRIPTION

The function B<gbatch_getbtd> is used to read the default user profile
parameters for the given host.

I<fd> is a file descriptor which was previously returned by a
successful call to gbatch_open(3).

I<defs> is a pointer to a structure which will on successful return,
contain the default user details.

=head1 RETURN VALUES

The function returns 0 if successful, otherwise an error code as
defined in the include file \fBgbatch.h\fR.

=head1 SEE ALSO

gbatch_getbtu(3),
gbatch_open(3),
gbatch_putbtd(3),
gbatch_putbtu(3).

=head1 COPYRIGHT

Copyright (c) 2009 Free Software Foundation, Inc.
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
