=head1 NAME

gbatch_putenv - insert an environment varible into a job.

=head1 SYNOPSIS

=for man
\&\fB#include <gbatch.h>\fR
.PP

=for html
<STRONG>#include &lt;gbatch.h&gt;</STRONG>
<br>

B<const char *gbatch_putenv(const apiBtjob *>I<jobp>B<, const char *>I<name>B<)>

=head1 DESCRIPTION

The function B<gbatch_putenv> is used to insert an environment variable
into a job string table.

I<jobp> is a pointer to a structure containing the details of the job.

I<name> is the environment varible required, in the form C<NAME=VALUE>.

=head1 RETURN VALUES

This function will return non-zero if successful otherwise zero if the
string table overflowed. In the latter case the contents of the job
structure should not be relied upon.  If in doubt copy the job
structure first.

=head1 SEE ALSO

gbatch_delarg(3),
gbatch_delenv(3),
gbatch_delredir(3),
gbatch_getarg(3),
gbatch_getdirect(3),
gbatch_getenv(3),
gbatch_getenvlist(3),
gbatch_getredir(3),
gbatch_gettitle(3),
gbatch_putarg(3),
gbatch_putarglist(3),
gbatch_putdirect(3),
gbatch_putenvlist(3),
gbatch_putredir(3),
gbatch_putredirlist(3),
gbatch_puttitle(3),
gbatch_setqueue(3).

=head1 COPYRIGHT

Copyright (c) 2009 Free Software Foundation, Inc.
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
