=head1 NAME

gbatch_jobchown - cahenge the owner of a job

=head1 SYNOPSIS

=for man
\&\fB#include <gbatch.h>\fR
.PP

=for html
<STRONG>#include &lt;gbatch.h&gt;</STRONG>
<br>

B<int gbatch_jobchown(const int>
I<fd>B<, const unsigned>
I<flags>B<, const slotno_t>
I<slot>B<, const char *>I<newowner>B<)>

=head1 DESCRIPTION

The function B<gbatch_jobchown()> is used to change the ownership of a job

I<fd> is a file descriptor which was previously returned by a
successful call to gbatch_open(3).

I<flags> is zero or C<GBATCH_FLAG_IGNORESEQ> to ignore recent changes
to the job list.

I<slot> is the slot number corresponding to the job as returned by
gbatch_joblist(3) or xb_jobfindslot(3).

I<newowner> is the user name of the prospective new owner.

=head1 RETURN VALUES

The function returns 0 if successful, otherwise an error code as
defined in the include file \fBgbatch.h\fR.

=head1 SEE ALSO

gbatch_jobchgrp(3),
gbatch_jobchmod(3),
gbatch_newgrp(3),
gbatch_varchown(3),
gbatch_varchgrp(3),
gbatch_varchmod(3).

=head1 COPYRIGHT

Copyright (c) 2009 Free Software Foundation, Inc.
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
