=head1 NAME

gbatch_delenv - delete an environment variable from a job structure

=head1 SYNOPSIS

=for man
\&\fB#include <gbatch.h>\fR
.PP

=for html
<STRONG>#include &lt;gbatch.h&gt;</STRONG>
<br>

B<int gbatch_delenv(const apiBtjob *>I<jobp>B<, const char *>I<name>B<)>

=head1 DESCRIPTION

The function B<gbatch_getenv> is used to delete an environment variable
from a job string table.

I<jobp> is a pointer to a structure containing the details of the job.

=for html
<P>The definition of the job structure is given in <a
href="BchAPI-7.html#Job_struct_def">a previous section</a> of this
manual.</P>

I<name> is the environment varible to be deleted.

=head1 RETURN VALUES

The result is non-zero if successful, or zero if the string table
overflowed, an unlikely event in the case of a deletion.

No error is reported if the specified variable does not exist.

=head1 NOTES

Environment variables common to all jobs may be held in a "static
environment file" to which the job structure environment variables
represent differences only. This routine will not affect entries in
the static environment file.

=head1 SEE ALSO

gbatch_delarg(3),
gbatch_delredir(3),
gbatch_getarg(3),
gbatch_getdirect(3),
gbatch_getenv(3),
gbatch_getenvlist(3),
gbatch_gethenv(3),
gbatch_getredir(3),
gbatch_gettitle(3),
gbatch_putarg(3),
gbatch_putarglist(3),
gbatch_putdirect(3),
gbatch_putenv(3),
gbatch_putenvlist(3),
gbatch_putredir(3),
gbatch_putredirlist(3),
gbatch_puttitle(3),
gbatch_setqueue(3).

=head1 COPYRIGHT

Copyright (c) 2009 Free Software Foundation, Inc.
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
