=head1 NAME

gbatch_newgrp - select new primary group

=head1 SYNOPSIS

=for man
\&\fB#include <gbatch.h>\fR
.PP

=for html
<STRONG>#include &lt;gbatch.h&gt;</STRONG>
<br>

B<int gbatch_newgrp(const int>
I<fd>B<, const char *>
I<group>B<)>

=head1 DESCRIPTION

The function B<gbatch_newgrp> is used to select a new primary group as the
user's primary group.

I<fd> is a file descriptor which was previously returned by a
successful call to gbatch_open(3).

I<group> is the required group name to be selected. If the user has
I<write admin file> privilege, this may be any valid group name,
otherwise the group must be the user's default groupp or one of the
user's supplementary groups.

=head1 RETURN VALUES

The function returns 0 if successful, otherwise an error code as
defined in the include file \fBgbatch.h\fR.

=head1 SEE ALSO

gbatch_open(3),
gbatch_close(3),
gbatch_jobmon(3),
gbatch_varmon(3).

=head1 COPYRIGHT

Copyright (c) 2009 Free Software Foundation, Inc.
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
