=head1 NAME

gbch-xmfilemon - X/Motif file monitor interface

=head1 SYNOPSIS

B<gbch-xmfilemon> &

=head1 DESCRIPTION

B<Gbch-xmfilemon> is a simple dialog interface to set up parameters for
gbch-filemon(1).

=head1 FILES

F<~/.gnubatch>
configuration file (home directory)

F<.gnubatch>
configuration file (current directory)

F<filemon.help>
message file

=head1 ENVIRONMENT

=over 4

=item FILEMONCONF

path name of alternative message file.

=back

=head1 SEE ALSO

gbch-filemon(1).

=head1 COPYRIGHT

Copyright (c) 2009 Free Software Foundation, Inc.
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
## LocalWords:  gbch-xmfilemon
