=head1 NAME

gbch-xq - GTK+ batch queue view

=head1 SYNOPSIS

B<gbch-xq>

=head1 DESCRIPTION

B<gbch-xq> is a fully interactive GTK+ alternative to the standard
queue manager gbch-q(1). As with gbch_q(1) the format of the screen display,
the help messages and the command keystrokes can be easily altered to
suit your requirements.

Unlike gbch-q(1) there are no specific command line options to
B<gbch-xq>.

=head1 FILES

F<~/.gnubatch>
configuration file (home directory)

F<.gnubatch>
configuration file (current directory)

F<xmbtq.help>
message file

=head1 SEE ALSO

gbch-q(1),
gbch-r(1),
gbch-user(1),
gbch-jdel(1),
gbch-jchange(1),
gbch-var,
gbch-jlist(1),
gbch-vlist(1).

=head1 COPYRIGHT

Copyright (c) 2009 Free Software Foundation, Inc.
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
## LocalWords:  gbch-q gbch-xq
