=head1 NAME

gbch-xuser - GTK+ user administration

=head1 SYNOPSIS

B<gbch-xuser> &

=head1 DESCRIPTION

B<gbch-xuser> is a fully interactive GTK+ alternative to the standard
user control program gbch-user(1), but only in the fully interactive
mode, so it cannot be started by a user without I<Write admin file>
privilege.

Unlike gbch-user(1) there are no specific command line options to
B<gbch-xuser>.

=head1 FILES

F<~/.gnubatch>
configuration file (home directory)

F<.gnubatch>
configuration file (current directory)

F<xmbtuser.help>
message file

=head1 ENVIRONMENT

=over 4

=item XMBTUSERCONF

path name of alternative message file.

=back

=head1 SEE ALSO

gbch-user(1),
gbch-ulist(1),
gbch-uchange(1),
gbch-uconv(8).

=head1 COPYRIGHT

Copyright (c) 2009 Free Software Foundation, Inc.
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
## LocalWords:  gbch-user gbch-xuser
