=head1 NAME

gbch-xmr - X/Motif batch job submission

=head1 SYNOPSIS

B<gbch-xmr> &

=head1 DESCRIPTION

B<Gbch-xmr> is a fully interactive Motif alternative to the standard tools
for submitting batch jobs, gbch-r(1) and gbch-rr(1). Jobs are submitted from
saved job files, which may have been created via "unqueue" from
gbch-q(1), gbch-xmq(1) or gbch-jdel(1), or created afresh within B<gbch-xmr>.

Unlike gbch-r(1) etc there are no specific command line options to
B<gbch-xmr>. The facility to change or specify resources settings for an
X11 (and hence Motif) program on the command line can be used.

=head1 FILES

F<~/.gnubatch>
configuration file (home directory)

F<.gnubatch>
configuration file (current directory)

F<xmbtr.help>
message file

=head1 ENVIRONMENT

=over 4

=item XMBTQCONF

path name of alternative message file.

=back

=head1 SEE ALSO

gbch-q(1),
gbch-r(1),
gbch-user(1),
gbch-jdel(1),
gbch-jchange(1),
gbch-jlist(1),
gbch-vlist(1),
gnubatch.conf(5),
gnubatch.hosts(5).

=head1 COPYRIGHT

Copyright (c) 2009 Free Software Foundation, Inc.
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
## LocalWords:  gbch-q BTQCONF gbch-xmr
