=head1 NAME

jobdump - support unqueue of job files

=head1 SYNOPSIS

B<jobdump> I<options>

=head1 DESCRIPTION

B<jobdump> is invoked by gbch-q(1), gbch-xmq(1) and gbch-jdel(1) to I<unqueue>
jobs when required.

It is not intended for general use and is not documented further.

=head1 SEE ALSO

gbch-q(1),
gbch-jdel(1),
gbch-xmq(1).

=head1 COPYRIGHT

Copyright (c) 2009 Free Software Foundation, Inc.
This is free software. You may redistribute copies of it under the
terms of the GNU General Public License
<http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

=head1 AUTHOR

John M Collins, Xi Software Ltd.

=cut

## Local Variables:
## mode: nroff
## End:
